#name: Push artifacts to another repository
#
#on: push
#
#env:
#    API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#
#jobs:
#  copy_artifacts_folder:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: cpina/github-action-push-to-another-repository@main
#        with:
#          source-directory: 'artifacts'
#          destination-github-username: 'gasperbr'
#          destination-repository-name: 'actions-output'
#          user-email: 'gasper@sushi.com'
#          target-branch: master

name: Push generated webpage to another repository
on: push
env:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
jobs:
  copy_artifacts_folder:
    runs-on: ubuntu-latest
    steps:
      - uses: nkoppel/push-files-to-another-repository@1.1.0
        with:
          source-files: 'artifacts/'
          destination-username: 'gasperbr'
          destination-repository: 'actions-output'
          destination-directory: 'artifacts'
          commit-email: 'gasper@sushi.com'
